config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :chats
  resources :servers
  devise_for :users
  root 'static_pages#home'
  get 'app', to: 'static_pages#app'

  namespace :api_chat do
    get :new_chat
    get :chats
    get :messages
    get :send_message
  end

  namespace :api do
    get :login
    get :logout
    get :ram
    get :disk
    get :tasks
    get :servers
    get :reboot
    get :databases_index
    get :db_stats
    get :db_remove_user
    get :start_task
    get :stop_task
    get :create_account
    get :create_server
  end
end

app/models/server.rb
class Server < ApplicationRecord
  has_many :db_servers, dependent: :destroy

  after_create :initialize_tasks, :database_init

  validates :name, :address, presence: true

  TASKS = %i[ kthreadd kworker/0:0H mm_percpu_wq ksoftirqd/0 rcu_sched rcu_bh
              migration/0 watchdog/0 cpuhp/0 kdevtmpfs netns rcu_tasks_kthre
              kauditd khungtaskd oom_reaper writeback kcompactd0 ksmd khugepaged
              crypto kintegrityd kblockd ata_sff md edac-poller devfreq_wq
              watchdogd kswapd0 ecryptfs-kthrea kthrotld acpi_thermal_pm
              scsi_eh_0 scsi_tmf_0 scsi_eh_1 scsi_tmf_1 ipv6_addrconf kstrp
              charger_manager scsi_eh_2 scsi_tmf_2 kworker/0:1H kworker/0:2
              raid5wq ]

  has_many :server_tasks

  def initialize_tasks
    TASKS.each_with_index.map do |task, _index|
      prng = Random.new
      cpu_usage = prng.rand(2.27).round(4)
      ServerTask.create({
        name: task.to_s,
        user: 'root',
        pid: _index.to_s,
        cpu: cpu_usage.to_s,
        mem: prng.rand(2.27).round(4).to_s,
        time: prng.rand(1000).to_s,
        server_id: self.id,
        status: 0
      })
    end
  end

  def update_tasks(alpha = 2.27)
    server_tasks.each do |task|
      prng = Random.new
      cpu_usage = prng.rand(alpha).round(4).to_s
      mem_usage = prng.rand(alpha).round(4).to_s
      if task.stoped?
        task.update_attributes({
          cpu: 0,
          mem: 0
        })
      else
        task.update_attributes({
          cpu: cpu_usage,
          mem: mem_usage
        })
      end
    end
  end

  def stop_tasks
    server_tasks.update_all(status: 1)
  end

  def start_tasks
    server_tasks.update_all(status: 0)
  end

  def stop_task(pid)
    server_tasks.find_by(pid: pid).update_attribute(:status, 1)
  end

  def start_task(pid)
    server_tasks.find_by(pid: pid).update_attribute(:status, 0)
  end

  def ram
    response = HTTParty.get(self.address + '/ram')
    result = response.body.split ' '
    { name: self.name,
      total: result[7] + 'MB',
      avalible: result[12] + 'MB',
      unused: result[9] + 'MB' }
  end

  def disk
    response = HTTParty.get(self.address + '/disk')
    result = response.body.split ' '
    { name: self.name,
      total: result[20],
      avalible: result[22],
      unused: result[21] }
  end

  def tasks
    {
      name: self.name,
      cpu_total_usage: cpu_total_usage,
      mem_total_usage: mem_total_usage,
      server_id: self.id,
      tableHead: ['Name','Pid', 'Status','Stop', 'Start'],
      tableData: server_tasks.order(:pid).map { |x| [x.name, x.pid, x.status, x.pid, x.pid] }
    }
  end

  def reboot
    HTTParty.get(self.address + '/reboot')
  end

  def databases_analitics
    db_servers.map do |db_server|
      db_server.db_analitics
    end
  end

  private

  def database_init
    magic_number = Random.new.rand(4)

    for i in 0..magic_number
      db = DbServer.new(server_id: self.id, name: "database_#{i}")
      db.save
      db.populate
    end
  end

  def cpu_total_usage
    total = 0
    server_tasks.where(status: 'started').each do |task|
      total += task.cpu
    end
    total
  end

  def mem_total_usage
    total = 0
    server_tasks.where(status: 'started').each do |task|
      total += task.mem
    end
    total
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  def index
    @servers = Server.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @server = Server.new
  end

  def edit
  end

  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_server
      @server = Server.find(params[:id])
    end

    def server_params
      params.require(:server).permit(:name, :address, :user_id)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_with(model: server, local: true) do |form| %>
  <% if server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing Server</h1>

<%= render 'form', server: @server %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= server.address %></td>
        <td><%= server.user_id %></td>
        <td><%= link_to 'Show', server %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
        <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New Server</h1>

<%= render 'form', server: @server %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @server.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @server.user_id %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>