config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :chats
  resources :servers
  devise_for :users
  root 'static_pages#home'
  get 'app', to: 'static_pages#app'

  namespace :api_chat do
    get :new_chat
    get :chats
    get :messages
    get :send_message
  end

  namespace :api do
    get :login
    get :logout
    get :ram
    get :disk
    get :tasks
    get :servers
    get :reboot
    get :databases_index
    get :db_stats
    get :db_remove_user
    get :start_task
    get :stop_task
    get :create_account
    get :create_server
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy

  def self.find_chat(params = {})
    result = Chat.find_by(from_user: params[:user_id],
                          to_user: params[:receiver_id])
    return result if result
    Chat.find_by(to_user: params[:user_id], from_user: params[:receiver_id])
  end

  def self.find_my_chats(params = {})
    result = []

    Chat.where(from_user: params[:user_id]).map { |chat|
      x = {
        chat_id: chat.id,
        partner_email: User.find(chat.to_user).email
      }
      result << x
    }

    Chat.where(to_user: params[:user_id]).map { |chat|
      x = {
        chat_id: chat.id,
        partner_email: User.find(chat.from_user).email
      }
      result << x
    }

    result
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:from_user, :to_user)
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: chat, local: true) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% chat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :from_user %>
    <%= form.number_field :from_user %>
  </div>

  <div class="field">
    <%= form.label :to_user %>
    <%= form.number_field :to_user %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chats</h1>

<table>
  <thead>
    <tr>
      <th>From user</th>
      <th>To user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.from_user %></td>
        <td><%= chat.to_user %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From user:</strong>
  <%= @chat.from_user %>
</p>

<p>
  <strong>To user:</strong>
  <%= @chat.to_user %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>